- src/config.c
Add a wee bit of debug as well. It's nice.
> Continue on terminating '}' in a config stanza.

- src/http.c
Unless status is 204 or 1xx (informational).
There are other cases where you are not permitted to write out the content-length, but they are
unsupported anyhow, see https://tools.ietf.org/html/rfc7230#section-3.3.2
> Always write out content-length;

- Makefile
- README.md
- src/accesslog.c
- src/cli.c
- src/config.c
- src/connection.c
- src/domain.c
- src/kore.c
- src/net.c
NO_SSL makes a bit more sense, especially for people who proxy their requests via nginx, apache, or similar.
> Rename BENCHMARK to NO_SSL.

- src/kore.c
When TLS isn't included, we shouldn't output "https".  We should instead output "http".
> Small tweak to kore's output when running a module

- src/http.c
- src/websocket.c
For the websocket handshake, Safari and Chrome will not accept this:
connection: keep-alive, Upgrade
(OK for Firefox)
Do not append keep-alive for CONN_PROTO_WEBSOCKET
> Fix websockets. Connection must be Upgrade, not keep-alive, Upgrade

- Makefile
I have fixed the Makefile, however (effectively) it wasn't wrong, I just never saw the following message:
```make: `kore' is up to date.```
> Don't link object files if not needed

- src/buf.c
There was an invalid boundary check when appending to a buffer. The consequence of this was that the POST data buffer was deterministically realloced.
I noticed this when debugging the memory usage for multipart post requests. I've created a small example that shows the error, see [my memory debug branch](https://github.com/CarlEkerot/kore/tree/ce-mem-debug).
To run it, start a server in debug mode, and send an arbitrary multipart POST request with the tool of your choice, for example:
```
curl -v -k -F file=@filename -H "Content-Length: 100000" https://127.0.0.1:8888/
```
On the server side, this yields:
```
[8983] src/mem.c:42 - [src/buf.c:25] Mallocing 100000 bytes
[8983] src/buf.c:36 - buf->offset: 0, len: 0, buf->length: 100000
.
.
.
[8983] src/buf.c:36 - buf->offset: 98456, len: …
```
> Fix off-by-one error when reallocing buffer

- src/net.c
Hi Joris,
If read/write is interrupted by signal before any bytes read, current behavior is giving up read/write operation. what i understand, with EPOLLET set on linux, it may lose the chance to read the socket buffer if it's last packet coming in. my change is to return OK and let the caller retry.  Could I have your comments, thanks.
Regards,
Ansen
> if read/write  return EINTR,retry

- includes/http.h
- includes/kore.h
- src/bsd.c
- src/buf.c
- src/cli.c
- src/config.c
- src/connection.c
- src/domain.c
- src/http.c
- src/kore.c
- src/linux.c
- src/mem.c
- src/module.c
- src/net.c
- src/pool.c
- src/utils.c
- src/websocket.c
- src/worker.c
Hi Joris - 
What a neat codebase you have created.  I added some management of buffers and file descriptors on shutdown.  This was to get Kore more clean when running under Valgrind.  I haven't touched anything related to memory management during the config parsing and validation process - from the comments it looks like you're planning to rework this at some point anyway?
Thanks and best wishes
Stig
> Add resource management as part of the kore shutdown process.

- src/worker.c
I discovered this on freebsd/clang. Please let me know if this PR needs anything more.
> error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'rlim_t' (aka 'long') [-Werror,-Wsign-compare]
> If we're iterating over rlimits, we should use rlim_t.

- includes/kore.h
- src/utils.c
This fixes a signed/unsigned comparison compiler error on NVIDIA Jetson TX1
$ gcc —version
gcc (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ make
… snip…
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -O2 -D_GNU_SOURCE=1 -c src/utils.c -o src/utils.o
src/utils.c: In function ‘kore_mem_find’:
src/utils.c:494:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if ((end - p) < len)
> cast difference between pointers as unsigned in kore_mem_find()

- includes/pgsql.h
- src/pgsql.c
Same as kore_pgsql_query_params but takes a va_list as last parameter
(non-v version takes a variable list of parameters).
Lets people write easier to call wrappers around the query calls. I use
it in a wrapper that takes next states (error, current, continue) as
arguments in a handler with multiple async queries.
Of course, I'm open to rewrite it the way you would want or you can write it your way.
> Added new function kore_pgsql_v_query_params().

- examples/cpp/conf/build.conf
- src/cli.c
This adds in compiling C++ with a C++ compiler, and also a `cxxflags` option similar to `cflags`. Corresponding issue is #131.
> Compile and link C++ with g++ instead of gcc

- src/cli.c
The build.conf file is left open when using `kore run`.
I'm experimenting with adding Capsicum support to kore and this was about the only unrestricted fd left.
Since kore forks worker processes afterwards it's left open in all of them. Better close it early :)
> Fix fd leak in cli_buildopt_parse()

- includes/http.h
to make includes order independent
previously defining
#include <kore/http.h>
#include <kore/kore.h>
wouldn't work as needed types in http.h are defined in kore.h
This solves it by including all needed headers.
> add missing includes

- includes/http.h
- src/http.c
If the application sets the server header, prevent the server from adding another one.
> Skip server header when set

- examples/video_stream/src/stream.c
With 2, we have max one element in the table because it's null
terminated...So we can't never get the end of the range.
Signed-off-by: Benjamin Hesmans <benjamin.hesmans@uclouvain.be>
> Small fix in video stream example

- .gitignore
After `make` on macOS there was created two files which are not stated in `.gitignore`
> Add some files for macOS

- src/cli.c
Some fix for building assets.
Before fix on macOS it builds some from hidden system files like .DS_Store, and probably just ignore hidden files.
```shell
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -Isrc -Isrc/includes -I/usr/local/include -I/opt/local/include -I/usr/local/opt/openssl/include  -g 
LDFLAGS=-dynamiclib -undefined suppress -flat_namespace 
building asset .DS_Store
compiling .DS_Store
```
And for some editor like Emacs temporary files with `~` or `#` it blows with error, for example for file: `index.html~`, so I added them to fix.
> Ignore hidden files and some temporary editor files in assets

- include/kore/kore.h
- src/websocket.c
Websocket memory leak fix when using kore_websocket_send() to send data.
> Websocket memory leak fix when using kore_websocket_send() to send data.
